from .annotation import AnnotationsView
from .config import ConfigsView
from .data import DataView
from .home import HomeView
from .model import ModelView
from .predictions import PredictionsView
from .settings import SettingsView
from .status import StatusView
from .train import TrainView
from .transformation import TransformView
from .test import TestView
